version: 1.0.{build}
build:
  project: YellowDrawer.Data.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
after_build:
- nuget pack src\YellowDrawer.Data.EF\YellowDrawer.Data.EF.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory src\YellowDrawer.Data.EF
- nuget pack src\YellowDrawer.Data.NHibernate\YellowDrawer.Data.NH.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory src\YellowDrawer.Data.NHibernate
- nuget pack src\YellowDrawer.Data.Common\YellowDrawer.Data.Common.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory src\YellowDrawer.Data.Common

test:
  categories:
    except:
      - Unit

image: Visual Studio 2017

artifacts:
- path: 'src\YellowDrawer.Data.EF\*.nupkg'
  name: YellowDrawer.Data.EF
- path: 'src\YellowDrawer.Data.NHibernate\*.nupkg'
  name: YellowDrawer.Data.NHibernate
- path: 'src\YellowDrawer.Data.Common\*.nupkg'
  name: YellowDrawer.Data.Common
  
install:
  - nuget restore YellowDrawer.Data.sln

deploy:
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Data.EF
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Data.NHibernate
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Data.Common
  
