version: 1.0.{build}
build:
  project: YellowDrawer.Data.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

  
after_build:
- nuget pack YellowDrawer.Data.EF\YellowDrawer.Data.EF.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory YellowDrawer.Data.EF
- nuget pack YellowDrawer.Data.NHibernate\YellowDrawer.Data.NH.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory YellowDrawer.Data.NHibernate
- nuget pack YellowDrawer.Data.Common\YellowDrawer.Data.Common.nuspec  -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory YellowDrawer.Data.Common

artifacts:
- path: 'YellowDrawer.Data.EF\*.nupkg'
  name: YellowDrawer.Data.EF
- path: 'YellowDrawer.Data.NHibernate\*.nupkg'
  name: YellowDrawer.Data.NHibernate
- path: 'YellowDrawer.Data.Common\*.nupkg'
  name: YellowDrawer.Data.Common
  
install:
  - nuget restore YellowDrawer.Data.sln
  - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
  - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - ps: dnvm install 1.0.0-rc1-update1
  - ps: dnvm use 1.0.0-rc1-update1

before_build:
 - ps: dnu restore
  
deploy:
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Data.EF
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Data.NHibernate
- provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: YellowDrawer.Data.Common
  
